esphome:
  name: nursery
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: bme280
    temperature: 
      id: "temperature"
      name: "Nursery Temperature"
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "Â°F"
    pressure:
      id: "pressure"
      name: "Nursery Pressure"
    humidity:
      id: "humidity"
      name: "Nursery Humidity"
    address: 0x77
    update_interval: 60s
    
i2c:
    sda: 4
    scl: 5